### PR TITLE
Add Python 3.9 to build

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by roycaihw** [comment]
waiting for the 3.8 & 3.9 jobs to finish: https://travis-ci.org/github/kubernetes-client/python-base/builds/745486231

/lgtm
/approve
/hold

**Comment by gliptak** [comment]
waiting for https://travis-ci.org/github/kubernetes-client/python-base/builds/745761288

maybe time to move build to GHA

**Comment by gliptak** [comment]
build was green although never reported back https://travis-ci.org/github/kubernetes-client/python-base/builds/745761288

current build https://travis-ci.org/github/kubernetes-client/python-base/builds/747758270

**Comment by gliptak** [comment]
https://travis-ci.org/github/kubernetes-client/python-base/builds/747758270 is green

**Comment by gliptak** [comment]
any other updates for this PR?

**Pull request merged**
