### PR TITLE
id/bearer token auth support for API client configuration

### PR DESCRIPTION
**Pull request by jroberts235**
Support for use of id/bearer token in kube.conf when auth'ing with kubernetes API

### CODE REVIEW

**Comment by mbohlool** [comment]
Please sign CLA and also prove a provider example that uses this.

**Comment by grillz** [comment]
CoreOS has a tool that writes the kubecfg this way. Regardless its a valid kubecfg so the client should be able to handle it.

**Comment by jroberts235** [comment]
CLA signed.

**Comment by mbohlool** [comment]
signature is not registered yet. Please try again.

**Comment by jroberts235** [comment]
CLA was signed Jan 19.

**Comment by mbohlool** [comment]
ref: https://github.com/kubernetes/community/blob/master/CLA.md

**Pull request closed without merging**
