### PR TITLE
Use select.poll() for exec on linux/darwin

### PR DESCRIPTION
**Pull request by jsun-splunk**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

For an **exec** call, the current `WSClient` implementation uses `select.select()` to wait for file descriptor that are ready for read. The `select.select()` method uses the `select()` system call for this. As the `select()` system call has a limitation where by it will return the following error if the [file descriptor # is greater than 1024](https://man7.org/linux/man-pages/man2/select.2.html).

```
Reason: filedescriptor out of range in select()
```

This limitation happens at scale when are running a large number of **exec** calls from a single client process. Once the filedescriptor number goes pass 1024 all future **exec** calls will experience the above error.

By switching to [select.poll()](https://docs.python.org/3.8/library/select.html#polling-objects) instead, we can over come this limitation. The caveat here is that `select.poll()` is only supported on unix based OS, where as `select.select()` is also support on Windows. However, even if this is the case, it would be better to use the `select.poll()` where possible so we can overcome this limitation even if it is on unix based OS.

#### Which issue(s) this PR fixes:

Similar problem was previously discussed in these issues. 
https://github.com/kubernetes-client/python-base/issues/53
https://github.com/kubernetes-client/python-base/issues/106

#### Special notes for your reviewer:

Another option here is to use `select.epoll()` instead of `select.poll()` for linux, however, I did not fully understand the difference between the two and did not felt confident enough to try epoll.

#### Does this PR introduce a user-facing change?

NONE

```release-note
Use select.poll() for exec on linux/darwin to improve scalability of WSClient
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by roycaihw** [comment]
/assign

Thanks for sending the fix! Please let us know when it's ready for review.

**Comment by jsun-splunk** [comment]
Hi @roycaihw - thanks for looking into this. I'm just waiting on some internal process to sign off the CLA. The PR is actually ready to be reviewed.

**Comment by jsun-splunk** [comment]
I signed it

**Comment by jsun-splunk** [comment]
i signed it

**Comment by roycaihw** [comment]
The CLA check still doesn't pass. Please make sure you've signed the CLA, and the email matches the one used in the Git commits.

**Comment by jsun-splunk** [comment]
hi @roycaihw,

Now this is merged, do you know how we can update the submodule in the top leve client (https://github.com/kubernetes-client/python/tree/master/kubernetes)? I can't seem to find any instructions on how to release the submodules.

Thanks!

**Comment by roycaihw** [comment]
Please follow [this instruction](https://github.com/kubernetes-client/python/blob/master/devel/submodules.md#update-submodule) to update the submodule and create a PR. Thanks!

**Pull request merged**
